name: my first github action 
on: [push]
jobs:
    print-hello-world:
      runs-on: ubuntu-latest
      steps:
          - run : echo "hello word"
          - run : echo "this is step number 2"
          - run : echo "this is step number 3"
          - run : echo "this is step number 4"
       
